---
title: "Untitled"
author: "Andy Barclay"
date: "May 18, 2018"
output: html_document
---

# Hello world

##Get packages
```{r library}

  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)

```

##Get data from knb site
```{r get escapment data}

esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1", method = "libcurl"), 
                stringsAsFactors = FALSE)
head(esc)

```

##Annual median escapments
```{r median esc}

median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount)) 

median_esc <- median_esc %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))

```

##Plotting median escapment
```{r plot median esc}

ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()

```

## Getting unique locations
```{r unique locations}

locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

```

```{r table locations}

datatable(locations)

```

#Here's a map of locations
```{r map locations}

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)

```
##Creating custom marker
```{r}
# Use a custom marker so Leaflet doesn't try to grab the marker images from 
# its CDN (this was brought up in 
# https://github.com/NCEAS/sasap-training/issues/22)
markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41
)
```

```{r}

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)

```

###Map here is has correct lattitudes
```{r}
locs <- locations %>% mutate(Longitude = abs(Longitude) * -1)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
```


